services:
  django:
    container_name: simple_lms
    build: .
    volumes:
      - ./code:/code
    ports:
      - "8001:8000"
    command: python manage.py runserver 0.0.0.0:8000
  postgres:
    container_name: simple_db
    image: postgres:16.1
    environment:
      POSTGRES_DB: simple_lms
      POSTGRES_USER: simple_user
      POSTGRES_PASSWORD: simple_password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5555:5432"